# Absenteeism at Work

## PROBLEM STATEMENT (purpose and value of a model)

In many businesses, absenteeism is a serious problem that negatively affects productivity, employee morale, and ultimately the organization's bottom line.'Absenteeism at work' depicts different reasons and factors that contribute to the employee's absence at work from July 2007 to July 2010 at a courier company in Brazil.

The problem statement is related to the Human Resources(HR) Analytics where the employee's absence can be validated using various reasons which can potentially impact the weightage for the decision of promotion and  elimination at the company.

Understanding the variables that lead to workplace absenteeism can help the human resources department to identify measures to lower its prevalence. The parameters taken are the connections between several personal, professional, and health-related aspects and absenteeism in order to know the reason and consequence for the absence according to HR rules and regulations. On the basis of the results, suggestions will be made for developing policies and programs to deal with absenteeism and support a healthy and effective workplace.

## Import and install python libraries

In [1]:
# import packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from xgboost import XGBClassifier
from scipy.stats import randint
from sklearn.metrics import make_scorer, recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
!pip install xgboost
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
!pip install imblearn
from imblearn.over_sampling import SMOTE
from sklearn.utils import resample
from imblearn.over_sampling import RandomOverSampler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import get_scorer_names
!pip install tensorflow
!pip install keras

Requirement already satisfied: xgboost in c:\users\aiswarya reddy\anaconda3\lib\site-packages (1.7.4)
Requirement already satisfied: scipy in c:\users\aiswarya reddy\anaconda3\lib\site-packages (from xgboost) (1.7.3)
Requirement already satisfied: numpy in c:\users\aiswarya reddy\anaconda3\lib\site-packages (from xgboost) (1.21.5)

WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)

Requirement already satisfied: imblearn in c:\users\aiswarya reddy\anaconda3\lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\users\aiswarya reddy\anaconda3\lib\site-packages (from imblearn) (0.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\aiswarya reddy\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\aiswarya reddy\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (2.2.0)
Requirement already satisfied: numpy>=1.17.3 in c:\users\aiswarya reddy\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.21.5)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\aiswarya reddy\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.0.2)
Requirement already satisfied: scipy>=1.3.2 in c:\users\aiswarya reddy\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.7.3)

WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -oblib (c:\users\aiswarya reddy\anaconda3\lib\site-packages)

ImportError: cannot import name 'get_scorer_names' from 'sklearn.metrics' (C:\Users\Aiswarya Reddy\anaconda3\lib\site-packages\sklearn\metrics\__init__.py)

## Set random seed

In [2]:
# set random seed to ensure that results are repeatable
np.random.seed(1)

##  Load data

In [3]:
# load data
aaw = pd.read_csv("C:\\Users\\Aiswarya Reddy\\Downloads\\Absenteeism_at_work.csv")

## Conduct initial exploration of the data

In [4]:
aaw.head(20)

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,"239,554",...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,"239,554",...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,"239,554",...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,"239,554",...,0,1,2,1,0,1,90,172,30,2
5,3,23,7,6,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,2
6,10,22,7,6,1,361,52,3,28,"239,554",...,0,1,1,1,0,4,80,172,27,8
7,20,23,7,6,1,260,50,11,36,"239,554",...,0,1,4,1,0,0,65,168,23,4
8,14,19,7,2,1,155,12,14,34,"239,554",...,0,1,2,1,0,0,95,196,25,40
9,1,22,7,2,1,235,11,14,37,"239,554",...,0,3,1,0,0,1,88,172,29,8
10,20,1,7,2,1,260,50,11,36,"239,554",...,0,1,4,1,0,0,65,168,23,8
11,20,1,7,3,1,260,50,11,36,"239,554",...,0,1,4,1,0,0,65,168,23,8
12,20,11,7,4,1,260,50,11,36,"239,554",...,0,1,4,1,0,0,65,168,23,8
13,3,11,7,4,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,1
14,3,23,7,4,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,4
15,24,14,7,6,1,246,25,16,41,"239,554",...,0,1,0,1,0,0,67,170,23,8
16,3,23,7,6,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,2
17,3,21,7,2,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,8
18,6,11,7,5,1,189,29,13,33,"239,554",...,0,1,2,0,0,2,69,167,25,8
19,33,23,8,4,1,248,25,14,47,"205,917",...,0,1,2,0,0,1,86,165,32,2

In [5]:
# generate a basic summary of the data
aaw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ID                               740 non-null    int64
 1   Reason for absence               740 non-null    int64
 2   Month of absence                 740 non-null    int64
 3   Day of the week                  740 non-null    int64
 4   Seasons                          740 non-null    int64
 5   Transportation expense           740 non-null    int64
 6   Distance from Residence to Work  740 non-null    int64
 7   Service time                     740 non-null    int64
 8   Age                              740 non-null    int64
 9   Work load Average/day            740 non-null    object
 10  Hit target                       740 non-null    int64
 11  Disciplinary failure             740 non-null    int64
 12  Education                        740 non-null    int64
 13  Son                              740 non-null    int64
 14  Social drinker                   740 non-null    int64
 15  Social smoker                    740 non-null    int64
 16  Pet                              740 non-null    int64
 17  Weight                           740 non-null    int64
 18  Height                           740 non-null    int64
 19  Body mass index                  740 non-null    int64
 20  Absenteeism time in hours        740 non-null    int64
dtypes: int64(20), object(1)
memory usage: 121.5+ KB

### Here we can observe that the Work load Average/day  column data type is object because of the comma present in between numbers

In [6]:
aaw.head(20)

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26,7,3,1,289,36,13,33,"239,554",...,0,1,2,1,0,1,90,172,30,4
1,36,0,7,3,1,118,13,18,50,"239,554",...,1,1,1,1,0,0,98,178,31,0
2,3,23,7,4,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,2
3,7,7,7,5,1,279,5,14,39,"239,554",...,0,1,2,1,1,0,68,168,24,4
4,11,23,7,5,1,289,36,13,33,"239,554",...,0,1,2,1,0,1,90,172,30,2
5,3,23,7,6,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,2
6,10,22,7,6,1,361,52,3,28,"239,554",...,0,1,1,1,0,4,80,172,27,8
7,20,23,7,6,1,260,50,11,36,"239,554",...,0,1,4,1,0,0,65,168,23,4
8,14,19,7,2,1,155,12,14,34,"239,554",...,0,1,2,1,0,0,95,196,25,40
9,1,22,7,2,1,235,11,14,37,"239,554",...,0,3,1,0,0,1,88,172,29,8
10,20,1,7,2,1,260,50,11,36,"239,554",...,0,1,4,1,0,0,65,168,23,8
11,20,1,7,3,1,260,50,11,36,"239,554",...,0,1,4,1,0,0,65,168,23,8
12,20,11,7,4,1,260,50,11,36,"239,554",...,0,1,4,1,0,0,65,168,23,8
13,3,11,7,4,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,1
14,3,23,7,4,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,4
15,24,14,7,6,1,246,25,16,41,"239,554",...,0,1,0,1,0,0,67,170,23,8
16,3,23,7,6,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,2
17,3,21,7,2,1,179,51,18,38,"239,554",...,0,1,0,1,0,0,89,170,31,8
18,6,11,7,5,1,189,29,13,33,"239,554",...,0,1,2,0,0,2,69,167,25,8
19,33,23,8,4,1,248,25,14,47,"205,917",...,0,1,2,0,0,1,86,165,32,2

In [7]:
# generate a statistical summary of the numeric value in the data
aaw.describe()

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Hit target,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
count,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000,740.000000
mean,18.017568,19.216216,6.324324,3.914865,2.544595,221.329730,29.631081,12.554054,36.450000,94.587838,0.054054,1.291892,1.018919,0.567568,0.072973,0.745946,79.035135,172.114865,26.677027,6.924324
std,11.021247,8.433406,3.436287,1.421675,1.111831,66.952223,14.836788,4.384873,6.478772,3.779313,0.226277,0.673238,1.098489,0.495749,0.260268,1.318258,12.883211,6.034995,4.285452,13.330998
min,1.000000,0.000000,0.000000,2.000000,1.000000,118.000000,5.000000,1.000000,27.000000,81.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,56.000000,163.000000,19.000000,0.000000
25%,9.000000,13.000000,3.000000,3.000000,2.000000,179.000000,16.000000,9.000000,31.000000,93.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,69.000000,169.000000,24.000000,2.000000
50%,18.000000,23.000000,6.000000,4.000000,3.000000,225.000000,26.000000,13.000000,37.000000,95.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,83.000000,170.000000,25.000000,3.000000
75%,28.000000,26.000000,9.000000,5.000000,4.000000,260.000000,50.000000,16.000000,40.000000,97.000000,0.000000,1.000000,2.000000,1.000000,0.000000,1.000000,89.000000,172.000000,31.000000,8.000000
max,36.000000,28.000000,12.000000,6.000000,4.000000,388.000000,52.000000,29.000000,58.000000,100.000000,1.000000,4.000000,4.000000,1.000000,1.000000,8.000000,108.000000,196.000000,38.000000,120.000000

In [8]:
# Check the missing values by summing the total na's for each variable
aaw.isna().sum()

ID                                 0
Reason for absence                 0
Month of absence                   0
Day of the week                    0
Seasons                            0
Transportation expense             0
Distance from Residence to Work    0
Service time                       0
Age                                0
Work load Average/day              0
Hit target                         0
Disciplinary failure               0
Education                          0
Son                                0
Social drinker                     0
Social smoker                      0
Pet                                0
Weight                             0
Height                             0
Body mass index                    0
Absenteeism time in hours          0
dtype: int64

## Process the data
* Conduct any data prepartion that should be done *BEFORE* the data split.
* Split the data.
* Conduct any data preparation that should be done *AFTER* the data split.

## Data prepartion that should be done BEFORE the data split

In [9]:
print (aaw.columns)

Index(['ID', 'Reason for absence', 'Month of absence', 'Day of the week',
       'Seasons', 'Transportation expense', 'Distance from Residence to Work',
       'Service time', 'Age', 'Work load Average/day ', 'Hit target',
       'Disciplinary failure', 'Education', 'Son', 'Social drinker',
       'Social smoker', 'Pet', 'Weight', 'Height', 'Body mass index',
       'Absenteeism time in hours'],
      dtype='object')

In [10]:
aaw.drop(['ID'], axis=1, inplace = True)

### Removing the comma to make the column Work load Average/day data type from object to integer

In [11]:
# replace commas in between numbers with an empty string in the "Work load Average/day " column
aaw['Work load Average/day '] = aaw['Work load Average/day '].str.replace(',','')

In [12]:
aaw['Work load Average/day '] = aaw['Work load Average/day '].astype(int)

In [13]:
aaw.head(5)

,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,Hit target,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,26,7,3,1,289,36,13,33,239554,97,0,1,2,1,0,1,90,172,30,4
1,0,7,3,1,118,13,18,50,239554,97,1,1,1,1,0,0,98,178,31,0
2,23,7,4,1,179,51,18,38,239554,97,0,1,0,1,0,0,89,170,31,2
3,7,7,5,1,279,5,14,39,239554,97,0,1,2,1,1,0,68,168,24,4
4,23,7,5,1,289,36,13,33,239554,97,0,1,2,1,0,1,90,172,30,2

In [14]:
# explore the dataframe columns to verify the changed columns (Here the column changed is Work load Average/day )
aaw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 20 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Reason for absence               740 non-null    int64
 1   Month of absence                 740 non-null    int64
 2   Day of the week                  740 non-null    int64
 3   Seasons                          740 non-null    int64
 4   Transportation expense           740 non-null    int64
 5   Distance from Residence to Work  740 non-null    int64
 6   Service time                     740 non-null    int64
 7   Age                              740 non-null    int64
 8   Work load Average/day            740 non-null    int32
 9   Hit target                       740 non-null    int64
 10  Disciplinary failure             740 non-null    int64
 11  Education                        740 non-null    int64
 12  Son                              740 non-null    int64
 13  Social drinker                   740 non-null    int64
 14  Social smoker                    740 non-null    int64
 15  Pet                              740 non-null    int64
 16  Weight                           740 non-null    int64
 17  Height                           740 non-null    int64
 18  Body mass index                  740 non-null    int64
 19  Absenteeism time in hours        740 non-null    int64
dtypes: int32(1), int64(19)
memory usage: 112.9 KB

### Creating a column Absence of Employee for the absence of the worker equal to or greater than 5 hours indicating the absence for 1 or more days

In [15]:
aaw['Absence of Employee'] = aaw['Absenteeism time in hours'].apply(lambda x: 1 if x >= 5 else 0)

In [16]:
aaw.head(20)

,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,Hit target,...,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours,Absence of Employee
0,26,7,3,1,289,36,13,33,239554,97,...,1,2,1,0,1,90,172,30,4,0
1,0,7,3,1,118,13,18,50,239554,97,...,1,1,1,0,0,98,178,31,0,0
2,23,7,4,1,179,51,18,38,239554,97,...,1,0,1,0,0,89,170,31,2,0
3,7,7,5,1,279,5,14,39,239554,97,...,1,2,1,1,0,68,168,24,4,0
4,23,7,5,1,289,36,13,33,239554,97,...,1,2,1,0,1,90,172,30,2,0
5,23,7,6,1,179,51,18,38,239554,97,...,1,0,1,0,0,89,170,31,2,0
6,22,7,6,1,361,52,3,28,239554,97,...,1,1,1,0,4,80,172,27,8,1
7,23,7,6,1,260,50,11,36,239554,97,...,1,4,1,0,0,65,168,23,4,0
8,19,7,2,1,155,12,14,34,239554,97,...,1,2,1,0,0,95,196,25,40,1
9,22,7,2,1,235,11,14,37,239554,97,...,3,1,0,0,1,88,172,29,8,1
10,1,7,2,1,260,50,11,36,239554,97,...,1,4,1,0,0,65,168,23,8,1
11,1,7,3,1,260,50,11,36,239554,97,...,1,4,1,0,0,65,168,23,8,1
12,11,7,4,1,260,50,11,36,239554,97,...,1,4,1,0,0,65,168,23,8,1
13,11,7,4,1,179,51,18,38,239554,97,...,1,0,1,0,0,89,170,31,1,0
14,23,7,4,1,179,51,18,38,239554,97,...,1,0,1,0,0,89,170,31,4,0
15,14,7,6,1,246,25,16,41,239554,97,...,1,0,1,0,0,67,170,23,8,1
16,23,7,6,1,179,51,18,38,239554,97,...,1,0,1,0,0,89,170,31,2,0
17,21,7,2,1,179,51,18,38,239554,97,...,1,0,1,0,0,89,170,31,8,1
18,11,7,5,1,189,29,13,33,239554,97,...,1,2,0,0,2,69,167,25,8,1
19,23,8,4,1,248,25,14,47,205917,92,...,1,2,0,0,1,86,165,32,2,0

## Encoding

In [17]:
# label encoding 

labelencoder = LabelEncoder()
aaw['Education'] = labelencoder.fit_transform(aaw['Education'])
aaw['Son'] = labelencoder.fit_transform(aaw['Son'])
aaw['Pet'] = labelencoder.fit_transform(aaw['Pet'])

In [18]:
# One-hot encoding 

Reason_for_absence = pd.get_dummies(aaw['Reason for absence'], prefix='Reason for absence')
Month_of_absence = pd.get_dummies(aaw['Month of absence'], prefix='Month of absence')
Day_of_the_week = pd.get_dummies(aaw['Day of the week'], prefix='Day of the week')
Seasons = pd.get_dummies(aaw['Seasons'], prefix='Seasons')
Disciplinary_failure = pd.get_dummies(aaw['Disciplinary failure'], prefix='Disciplinary failure')
Social_drinker = pd.get_dummies(aaw['Social drinker'], prefix='Social drinker')
Social_smoker = pd.get_dummies(aaw['Social smoker'], prefix='Social smoker')

# Concatenating one-hot encoded variables with the original data
aaw = pd.concat([aaw,Reason_for_absence,Month_of_absence,Day_of_the_week,
       Seasons,Disciplinary_failure,Social_drinker,
       Social_smoker], axis=1)

aaw = aaw.drop(['Reason for absence', 'Month of absence', 'Day of the week',
       'Seasons', 'Disciplinary failure', 'Social drinker',
       'Social smoker'], axis=1)

In [19]:
aaw.head(10)

,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,Hit target,Education,Son,Pet,Weight,...,Seasons_1,Seasons_2,Seasons_3,Seasons_4,Disciplinary failure_0,Disciplinary failure_1,Social drinker_0,Social drinker_1,Social smoker_0,Social smoker_1
0,289,36,13,33,239554,97,0,2,1,90,...,1,0,0,0,1,0,0,1,1,0
1,118,13,18,50,239554,97,0,1,0,98,...,1,0,0,0,0,1,0,1,1,0
2,179,51,18,38,239554,97,0,0,0,89,...,1,0,0,0,1,0,0,1,1,0
3,279,5,14,39,239554,97,0,2,0,68,...,1,0,0,0,1,0,0,1,0,1
4,289,36,13,33,239554,97,0,2,1,90,...,1,0,0,0,1,0,0,1,1,0
5,179,51,18,38,239554,97,0,0,0,89,...,1,0,0,0,1,0,0,1,1,0
6,361,52,3,28,239554,97,0,1,3,80,...,1,0,0,0,1,0,0,1,1,0
7,260,50,11,36,239554,97,0,4,0,65,...,1,0,0,0,1,0,0,1,1,0
8,155,12,14,34,239554,97,0,2,0,95,...,1,0,0,0,1,0,0,1,1,0
9,235,11,14,37,239554,97,2,1,1,88,...,1,0,0,0,1,0,1,0,1,0

In [20]:
aaw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 70 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Transportation expense           740 non-null    int64
 1   Distance from Residence to Work  740 non-null    int64
 2   Service time                     740 non-null    int64
 3   Age                              740 non-null    int64
 4   Work load Average/day            740 non-null    int32
 5   Hit target                       740 non-null    int64
 6   Education                        740 non-null    int64
 7   Son                              740 non-null    int64
 8   Pet                              740 non-null    int64
 9   Weight                           740 non-null    int64
 10  Height                           740 non-null    int64
 11  Body mass index                  740 non-null    int64
 12  Absenteeism time in hours        740 non-null    int64
 13  Absence of Employee              740 non-null    int64
 14  Reason for absence_0             740 non-null    uint8
 15  Reason for absence_1             740 non-null    uint8
 16  Reason for absence_2             740 non-null    uint8
 17  Reason for absence_3             740 non-null    uint8
 18  Reason for absence_4             740 non-null    uint8
 19  Reason for absence_5             740 non-null    uint8
 20  Reason for absence_6             740 non-null    uint8
 21  Reason for absence_7             740 non-null    uint8
 22  Reason for absence_8             740 non-null    uint8
 23  Reason for absence_9             740 non-null    uint8
 24  Reason for absence_10            740 non-null    uint8
 25  Reason for absence_11            740 non-null    uint8
 26  Reason for absence_12            740 non-null    uint8
 27  Reason for absence_13            740 non-null    uint8
 28  Reason for absence_14            740 non-null    uint8
 29  Reason for absence_15            740 non-null    uint8
 30  Reason for absence_16            740 non-null    uint8
 31  Reason for absence_17            740 non-null    uint8
 32  Reason for absence_18            740 non-null    uint8
 33  Reason for absence_19            740 non-null    uint8
 34  Reason for absence_21            740 non-null    uint8
 35  Reason for absence_22            740 non-null    uint8
 36  Reason for absence_23            740 non-null    uint8
 37  Reason for absence_24            740 non-null    uint8
 38  Reason for absence_25            740 non-null    uint8
 39  Reason for absence_26            740 non-null    uint8
 40  Reason for absence_27            740 non-null    uint8
 41  Reason for absence_28            740 non-null    uint8
 42  Month of absence_0               740 non-null    uint8
 43  Month of absence_1               740 non-null    uint8
 44  Month of absence_2               740 non-null    uint8
 45  Month of absence_3               740 non-null    uint8
 46  Month of absence_4               740 non-null    uint8
 47  Month of absence_5               740 non-null    uint8
 48  Month of absence_6               740 non-null    uint8
 49  Month of absence_7               740 non-null    uint8
 50  Month of absence_8               740 non-null    uint8
 51  Month of absence_9               740 non-null    uint8
 52  Month of absence_10              740 non-null    uint8
 53  Month of absence_11              740 non-null    uint8
 54  Month of absence_12              740 non-null    uint8
 55  Day of the week_2                740 non-null    uint8
 56  Day of the week_3                740 non-null    uint8
 57  Day of the week_4                740 non-null    uint8
 58  Day of the week_5                740 non-null    uint8
 59  Day of the week_6                740 non-null    uint8
 60  Seasons_1                        740 non-null    uint8
 61  Seasons_2                        740 non-null    uint8
 62  Seasons_3                        740 non-null    uint8
 63  Seasons_4                        740 non-null    uint8
 64  Disciplinary failure_0           740 non-null    uint8
 65  Disciplinary failure_1           740 non-null    uint8
 66  Social drinker_0                 740 non-null    uint8
 67  Social drinker_1                 740 non-null    uint8
 68  Social smoker_0                  740 non-null    uint8
 69  Social smoker_1                  740 non-null    uint8
dtypes: int32(1), int64(13), uint8(56)
memory usage: 118.6 KB

## Split data (train/test)

In [21]:
X = aaw.drop('Absence of Employee', axis=1)
y = aaw['Absence of Employee']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=1)

In [23]:
y_train

273    0
544    0
634    0
504    0
425    1
      ..
645    0
715    0
72     1
235    0
37     0
Name: Absence of Employee, Length: 518, dtype: int64

## Conduct any data prepartion that should be done AFTER the data split

## Scaling

In [24]:
# create a standard scaler and fit it to the training set of predictors
scaler = preprocessing.StandardScaler()
cols_to_stdize = ['Transportation expense', 'Distance from Residence to Work', 
                   'Service time', 'Age', 'Work load Average/day ', 'Weight', 'Height', 
                   'Body mass index']                
               
# Transform the predictors of training and validation sets
X_train[cols_to_stdize] = scaler.fit_transform(X_train[cols_to_stdize]) # train_predictors is not a numpy array


X_test[cols_to_stdize] = scaler.transform(X_test[cols_to_stdize]) # validation_target is now a series object

## Balancing data

In [26]:
ros = RandomOverSampler(random_state=1)
X_train, y_train = ros.fit_resample(X_train, y_train)
y_train.value_counts()

0    320
1    320
Name: Absence of Employee, dtype: int64

## Regularization of data

In [36]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras import regularizers

# Define the number of classes
num_classes = 1

# Define the input shape
input_dim = X_train.shape[1]

# Define the model
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=input_dim, kernel_regularizer=regularizers.l2(0.001)))
model.add(Dropout(0.5))
model.add(Dense(32, activation='relu', kernel_regularizer=regularizers.l2(0.001)))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

## Early stopping of data

In [37]:
from keras.callbacks import EarlyStopping

# define early stopping
early_stop = EarlyStopping(monitor='categorical_crossentropy', patience=10)

# fit the model with early stopping
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test), callbacks=[early_stop])

Epoch 1/100
 1/20 [>.............................] - ETA: 15s - loss: 0.1093 - accuracy: 0.4375WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 1s 8ms/step - loss: 0.1014 - accuracy: 0.5000 - val_loss: 0.0937 - val_accuracy: 0.3649
Epoch 2/100
 1/20 [>.............................] - ETA: 0s - loss: 0.0937 - accuracy: 0.7188WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.0884 - accuracy: 0.5000 - val_loss: 0.0831 - val_accuracy: 0.3649
Epoch 3/100
 1/20 [>.............................] - ETA: 0s - loss: 0.0831 - accuracy: 0.3125WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.0796 - accuracy: 0.5000 - val_loss: 0.0764 - val_accuracy: 0.3649
Epoch 4/100
 1/20 [>.............................] - ETA: 0s - loss: 0.0764 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.0747 - accuracy: 0.5000 - val_loss: 0.0735 - val_accuracy: 0.3649
Epoch 5/100
 1/20 [>.............................] - ETA: 0s - loss: 0.0735 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.0736 - accuracy: 0.5000 - val_loss: 0.0744 - val_accuracy: 0.3649
Epoch 6/100
 1/20 [>.............................] - ETA: 0s - loss: 0.0744 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.0764 - accuracy: 0.5000 - val_loss: 0.0793 - val_accuracy: 0.3649
Epoch 7/100
 1/20 [>.............................] - ETA: 0s - loss: 0.0793 - accuracy: 0.3125WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 3ms/step - loss: 0.0830 - accuracy: 0.5000 - val_loss: 0.0877 - val_accuracy: 0.3649
Epoch 8/100
 1/20 [>.............................] - ETA: 0s - loss: 0.0877 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.0935 - accuracy: 0.5000 - val_loss: 0.1006 - val_accuracy: 0.3649
Epoch 9/100
 1/20 [>.............................] - ETA: 0s - loss: 0.1006 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.1086 - accuracy: 0.5000 - val_loss: 0.1180 - val_accuracy: 0.3649
Epoch 10/100
 1/20 [>.............................] - ETA: 0s - loss: 0.1180 - accuracy: 0.5938WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.1277 - accuracy: 0.5000 - val_loss: 0.1395 - val_accuracy: 0.3649
Epoch 11/100
 1/20 [>.............................] - ETA: 0s - loss: 0.1395 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.1515 - accuracy: 0.5000 - val_loss: 0.1656 - val_accuracy: 0.3649
Epoch 12/100
 1/20 [>.............................] - ETA: 0s - loss: 0.1656 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.1797 - accuracy: 0.5000 - val_loss: 0.1960 - val_accuracy: 0.3649
Epoch 13/100
 1/20 [>.............................] - ETA: 0s - loss: 0.1960 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.2122 - accuracy: 0.5000 - val_loss: 0.2306 - val_accuracy: 0.3649
Epoch 14/100
 1/20 [>.............................] - ETA: 0s - loss: 0.2306 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.2490 - accuracy: 0.5000 - val_loss: 0.2699 - val_accuracy: 0.3649
Epoch 15/100
 1/20 [>.............................] - ETA: 0s - loss: 0.2699 - accuracy: 0.4062WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.2910 - accuracy: 0.5000 - val_loss: 0.3149 - val_accuracy: 0.3649
Epoch 16/100
 1/20 [>.............................] - ETA: 0s - loss: 0.3149 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.3370 - accuracy: 0.5000 - val_loss: 0.3624 - val_accuracy: 0.3649
Epoch 17/100
 1/20 [>.............................] - ETA: 0s - loss: 0.3624 - accuracy: 0.6250WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.3863 - accuracy: 0.5000 - val_loss: 0.4138 - val_accuracy: 0.3649
Epoch 18/100
 1/20 [>.............................] - ETA: 0s - loss: 0.4138 - accuracy: 0.3750WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.4409 - accuracy: 0.5000 - val_loss: 0.4709 - val_accuracy: 0.3649
Epoch 19/100
 1/20 [>.............................] - ETA: 0s - loss: 0.4709 - accuracy: 0.3750WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.4990 - accuracy: 0.5000 - val_loss: 0.5304 - val_accuracy: 0.3649
Epoch 20/100
 1/20 [>.............................] - ETA: 0s - loss: 0.5304 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.5605 - accuracy: 0.5000 - val_loss: 0.5946 - val_accuracy: 0.3649
Epoch 21/100
 1/20 [>.............................] - ETA: 0s - loss: 0.5946 - accuracy: 0.3438WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.6272 - accuracy: 0.5000 - val_loss: 0.6637 - val_accuracy: 0.3649
Epoch 22/100

 1/20 [>.............................] - ETA: 0s - loss: 0.6637 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.6984 - accuracy: 0.5000 - val_loss: 0.7371 - val_accuracy: 0.3649
Epoch 23/100
 1/20 [>.............................] - ETA: 0s - loss: 0.7371 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.7723 - accuracy: 0.5000 - val_loss: 0.8125 - val_accuracy: 0.3649
Epoch 24/100
 1/20 [>.............................] - ETA: 0s - loss: 0.8125 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.8520 - accuracy: 0.5000 - val_loss: 0.8956 - val_accuracy: 0.3649
Epoch 25/100
 1/20 [>.............................] - ETA: 0s - loss: 0.8956 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 0.9356 - accuracy: 0.5000 - val_loss: 0.9816 - val_accuracy: 0.3649
Epoch 26/100
 1/20 [>.............................] - ETA: 0s - loss: 0.9816 - accuracy: 0.6250WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 1.0243 - accuracy: 0.5000 - val_loss: 1.0735 - val_accuracy: 0.3649
Epoch 27/100
 1/20 [>.............................] - ETA: 0s - loss: 1.0735 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 1.1181 - accuracy: 0.5000 - val_loss: 1.1676 - val_accuracy: 0.3649
Epoch 28/100
 1/20 [>.............................] - ETA: 0s - loss: 1.1676 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 1.2141 - accuracy: 0.5000 - val_loss: 1.2662 - val_accuracy: 0.3649
Epoch 29/100
 1/20 [>.............................] - ETA: 0s - loss: 1.2662 - accuracy: 0.5938WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 1.3142 - accuracy: 0.5000 - val_loss: 1.3688 - val_accuracy: 0.3649
Epoch 30/100
 1/20 [>.............................] - ETA: 0s - loss: 1.3688 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 1.4192 - accuracy: 0.5000 - val_loss: 1.4759 - val_accuracy: 0.3649
Epoch 31/100
 1/20 [>.............................] - ETA: 0s - loss: 1.4759 - accuracy: 0.3438WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 1.5285 - accuracy: 0.5000 - val_loss: 1.5864 - val_accuracy: 0.3649
Epoch 32/100
 1/20 [>.............................] - ETA: 0s - loss: 1.5864 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 1.6400 - accuracy: 0.5000 - val_loss: 1.7004 - val_accuracy: 0.3649
Epoch 33/100
 1/20 [>.............................] - ETA: 0s - loss: 1.7004 - accuracy: 0.4375WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 1.7579 - accuracy: 0.5000 - val_loss: 1.8215 - val_accuracy: 0.3649
Epoch 34/100
 1/20 [>.............................] - ETA: 0s - loss: 1.8215 - accuracy: 0.4062WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 1.8783 - accuracy: 0.5000 - val_loss: 1.9426 - val_accuracy: 0.3649
Epoch 35/100
 1/20 [>.............................] - ETA: 0s - loss: 1.9426 - accuracy: 0.3125WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 2.0000 - accuracy: 0.5000 - val_loss: 2.0647 - val_accuracy: 0.3649
Epoch 36/100
 1/20 [>.............................] - ETA: 0s - loss: 2.0647 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 2.1259 - accuracy: 0.5000 - val_loss: 2.1943 - val_accuracy: 0.3649
Epoch 37/100
 1/20 [>.............................] - ETA: 0s - loss: 2.1943 - accuracy: 0.5938WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 2.2588 - accuracy: 0.5000 - val_loss: 2.3309 - val_accuracy: 0.3649
Epoch 38/100
 1/20 [>.............................] - ETA: 0s - loss: 2.3309 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 2.3968 - accuracy: 0.5000 - val_loss: 2.4697 - val_accuracy: 0.3649
Epoch 39/100
 1/20 [>.............................] - ETA: 0s - loss: 2.4697 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 2.5379 - accuracy: 0.5000 - val_loss: 2.6133 - val_accuracy: 0.3649
Epoch 40/100
 1/20 [>.............................] - ETA: 0s - loss: 2.6133 - accuracy: 0.3750WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 2.6832 - accuracy: 0.5000 - val_loss: 2.7600 - val_accuracy: 0.3649
Epoch 41/100
 1/20 [>.............................] - ETA: 0s - loss: 2.7600 - accuracy: 0.3438WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 2.8330 - accuracy: 0.5000 - val_loss: 2.9136 - val_accuracy: 0.3649
Epoch 42/100
 1/20 [>.............................] - ETA: 0s - loss: 2.9136 - accuracy: 0.3750WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 2.9912 - accuracy: 0.5000 - val_loss: 3.0758 - val_accuracy: 0.3649
Epoch 43/100
 1/20 [>.............................] - ETA: 0s - loss: 3.0758 - accuracy: 0.4375WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 3.1467 - accuracy: 0.5000 - val_loss: 3.2289 - val_accuracy: 0.3649
Epoch 44/100
 1/20 [>.............................] - ETA: 0s - loss: 3.2289 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 3.3066 - accuracy: 0.5000 - val_loss: 3.3931 - val_accuracy: 0.3649
Epoch 45/100
 1/20 [>.............................] - ETA: 0s - loss: 3.3931 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 3.4746 - accuracy: 0.5000 - val_loss: 3.5642 - val_accuracy: 0.3649
Epoch 46/100
 1/20 [>.............................] - ETA: 0s - loss: 3.5642 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 3.6470 - accuracy: 0.5000 - val_loss: 3.7381 - val_accuracy: 0.3649
Epoch 47/100
 1/20 [>.............................] - ETA: 0s - loss: 3.7381 - accuracy: 0.5938WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 3.8191 - accuracy: 0.5000 - val_loss: 3.9111 - val_accuracy: 0.3649
Epoch 48/100
 1/20 [>.............................] - ETA: 0s - loss: 3.9111 - accuracy: 0.3750WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 3.9991 - accuracy: 0.5000 - val_loss: 4.0943 - val_accuracy: 0.3649
Epoch 49/100
 1/20 [>.............................] - ETA: 0s - loss: 4.0943 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 4.1790 - accuracy: 0.5000 - val_loss: 4.2727 - val_accuracy: 0.3649
Epoch 50/100
 1/20 [>.............................] - ETA: 0s - loss: 4.2727 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 4.3590 - accuracy: 0.5000 - val_loss: 4.4575 - val_accuracy: 0.3649
Epoch 51/100
 1/20 [>.............................] - ETA: 0s - loss: 4.4575 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 4.5466 - accuracy: 0.5000 - val_loss: 4.6455 - val_accuracy: 0.3649
Epoch 52/100
 1/20 [>.............................] - ETA: 0s - loss: 4.6455 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 4.7332 - accuracy: 0.5000 - val_loss: 4.8315 - val_accuracy: 0.3649
Epoch 53/100
 1/20 [>.............................] - ETA: 0s - loss: 4.8315 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 4.9255 - accuracy: 0.5000 - val_loss: 5.0321 - val_accuracy: 0.3649
Epoch 54/100
 1/20 [>.............................] - ETA: 0s - loss: 5.0321 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 5.1279 - accuracy: 0.5000 - val_loss: 5.2352 - val_accuracy: 0.3649
Epoch 55/100
 1/20 [>.............................] - ETA: 0s - loss: 5.2352 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 5.3326 - accuracy: 0.5000 - val_loss: 5.4408 - val_accuracy: 0.3649
Epoch 56/100
 1/20 [>.............................] - ETA: 0s - loss: 5.4408 - accuracy: 0.6562WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 5.5377 - accuracy: 0.5000 - val_loss: 5.6476 - val_accuracy: 0.3649
Epoch 57/100
 1/20 [>.............................] - ETA: 0s - loss: 5.6476 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 5.7487 - accuracy: 0.5000 - val_loss: 5.8606 - val_accuracy: 0.3649
Epoch 58/100
 1/20 [>.............................] - ETA: 0s - loss: 5.8606 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 5.9611 - accuracy: 0.5000 - val_loss: 6.0727 - val_accuracy: 0.3649
Epoch 59/100
 1/20 [>.............................] - ETA: 0s - loss: 6.0727 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 6.1764 - accuracy: 0.5000 - val_loss: 6.2896 - val_accuracy: 0.3649
Epoch 60/100
 1/20 [>.............................] - ETA: 0s - loss: 6.2896 - accuracy: 0.6250WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 6.3924 - accuracy: 0.5000 - val_loss: 6.5084 - val_accuracy: 0.3649
Epoch 61/100
 1/20 [>.............................] - ETA: 0s - loss: 6.5084 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 6.6118 - accuracy: 0.5000 - val_loss: 6.7274 - val_accuracy: 0.3649
Epoch 62/100
 1/20 [>.............................] - ETA: 0s - loss: 6.7274 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 6.8311 - accuracy: 0.5000 - val_loss: 6.9506 - val_accuracy: 0.3649
Epoch 63/100
 1/20 [>.............................] - ETA: 0s - loss: 6.9506 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 7.0645 - accuracy: 0.5000 - val_loss: 7.1887 - val_accuracy: 0.3649
Epoch 64/100

 1/20 [>.............................] - ETA: 0s - loss: 7.1887 - accuracy: 0.4375WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 7.2993 - accuracy: 0.5000 - val_loss: 7.4208 - val_accuracy: 0.3649
Epoch 65/100
 1/20 [>.............................] - ETA: 0s - loss: 7.4208 - accuracy: 0.3750WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 7.5347 - accuracy: 0.5000 - val_loss: 7.6591 - val_accuracy: 0.3649
Epoch 66/100
 1/20 [>.............................] - ETA: 0s - loss: 7.6591 - accuracy: 0.6250WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 7.7728 - accuracy: 0.5000 - val_loss: 7.8997 - val_accuracy: 0.3649
Epoch 67/100
 1/20 [>.............................] - ETA: 0s - loss: 7.8997 - accuracy: 0.6562WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 8.0150 - accuracy: 0.5000 - val_loss: 8.1434 - val_accuracy: 0.3649
Epoch 68/100
 1/20 [>.............................] - ETA: 0s - loss: 8.1434 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 8.2618 - accuracy: 0.5000 - val_loss: 8.3926 - val_accuracy: 0.3649
Epoch 69/100
 1/20 [>.............................] - ETA: 0s - loss: 8.3926 - accuracy: 0.4062WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 8.5134 - accuracy: 0.5000 - val_loss: 8.6460 - val_accuracy: 0.3649
Epoch 70/100
 1/20 [>.............................] - ETA: 0s - loss: 8.6460 - accuracy: 0.5938WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 8.7668 - accuracy: 0.5000 - val_loss: 8.9044 - val_accuracy: 0.3649
Epoch 71/100
 1/20 [>.............................] - ETA: 0s - loss: 8.9044 - accuracy: 0.4375WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 9.0290 - accuracy: 0.5000 - val_loss: 9.1677 - val_accuracy: 0.3649
Epoch 72/100
 1/20 [>.............................] - ETA: 0s - loss: 9.1677 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 9.2911 - accuracy: 0.5000 - val_loss: 9.4290 - val_accuracy: 0.3649
Epoch 73/100
 1/20 [>.............................] - ETA: 0s - loss: 9.4290 - accuracy: 0.6562WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 9.5595 - accuracy: 0.5000 - val_loss: 9.7032 - val_accuracy: 0.3649
Epoch 74/100
 1/20 [>.............................] - ETA: 0s - loss: 9.7032 - accuracy: 0.5938WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 9.8297 - accuracy: 0.5000 - val_loss: 9.9729 - val_accuracy: 0.3649
Epoch 75/100
 1/20 [>.............................] - ETA: 0s - loss: 9.9729 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 10.1041 - accuracy: 0.5000 - val_loss: 10.2468 - val_accuracy: 0.3649
Epoch 76/100
 1/20 [>.............................] - ETA: 0s - loss: 10.2468 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 10.3790 - accuracy: 0.5000 - val_loss: 10.5277 - val_accuracy: 0.3649
Epoch 77/100
 1/20 [>.............................] - ETA: 0s - loss: 10.5277 - accuracy: 0.3438WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 10.6600 - accuracy: 0.5000 - val_loss: 10.8070 - val_accuracy: 0.3649
Epoch 78/100
 1/20 [>.............................] - ETA: 0s - loss: 10.8070 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 10.9437 - accuracy: 0.5000 - val_loss: 11.0963 - val_accuracy: 0.3649
Epoch 79/100
 1/20 [>.............................] - ETA: 0s - loss: 11.0963 - accuracy: 0.3125WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 11.2380 - accuracy: 0.5000 - val_loss: 11.3904 - val_accuracy: 0.3649
Epoch 80/100
 1/20 [>.............................] - ETA: 0s - loss: 11.3904 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 11.5300 - accuracy: 0.5000 - val_loss: 11.6838 - val_accuracy: 0.3649
Epoch 81/100
 1/20 [>.............................] - ETA: 0s - loss: 11.6838 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 11.8244 - accuracy: 0.5000 - val_loss: 11.9799 - val_accuracy: 0.3649
Epoch 82/100
 1/20 [>.............................] - ETA: 0s - loss: 11.9799 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 12.1203 - accuracy: 0.5000 - val_loss: 12.2765 - val_accuracy: 0.3649
Epoch 83/100
 1/20 [>.............................] - ETA: 0s - loss: 12.2765 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 12.4170 - accuracy: 0.5000 - val_loss: 12.5729 - val_accuracy: 0.3649
Epoch 84/100
 1/20 [>.............................] - ETA: 0s - loss: 12.5729 - accuracy: 0.6250WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 12.7075 - accuracy: 0.5000 - val_loss: 12.8609 - val_accuracy: 0.3649

Epoch 85/100
 1/20 [>.............................] - ETA: 0s - loss: 12.8609 - accuracy: 0.3125WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 13.0065 - accuracy: 0.5000 - val_loss: 13.1637 - val_accuracy: 0.3649
Epoch 86/100
 1/20 [>.............................] - ETA: 0s - loss: 13.1637 - accuracy: 0.5938WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 13.3151 - accuracy: 0.5000 - val_loss: 13.4788 - val_accuracy: 0.3649
Epoch 87/100
 1/20 [>.............................] - ETA: 0s - loss: 13.4788 - accuracy: 0.6250WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 13.6211 - accuracy: 0.5000 - val_loss: 13.7819 - val_accuracy: 0.3649
Epoch 88/100
 1/20 [>.............................] - ETA: 0s - loss: 13.7819 - accuracy: 0.6875WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 13.9281 - accuracy: 0.5000 - val_loss: 14.0925 - val_accuracy: 0.3649
Epoch 89/100
 1/20 [>.............................] - ETA: 0s - loss: 14.0925 - accuracy: 0.3750WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 14.2476 - accuracy: 0.5000 - val_loss: 14.4163 - val_accuracy: 0.3649
Epoch 90/100
 1/20 [>.............................] - ETA: 0s - loss: 14.4163 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 14.5644 - accuracy: 0.5000 - val_loss: 14.7289 - val_accuracy: 0.3649
Epoch 91/100
 1/20 [>.............................] - ETA: 0s - loss: 14.7289 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 14.8794 - accuracy: 0.5000 - val_loss: 15.0473 - val_accuracy: 0.3649
Epoch 92/100
 1/20 [>.............................] - ETA: 0s - loss: 15.0473 - accuracy: 0.5000WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 15.1982 - accuracy: 0.5000 - val_loss: 15.3668 - val_accuracy: 0.3649
Epoch 93/100
 1/20 [>.............................] - ETA: 0s - loss: 15.3668 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 15.5265 - accuracy: 0.5000 - val_loss: 15.7018 - val_accuracy: 0.3649
Epoch 94/100
 1/20 [>.............................] - ETA: 0s - loss: 15.7018 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 15.8584 - accuracy: 0.5000 - val_loss: 16.0310 - val_accuracy: 0.3649
Epoch 95/100
 1/20 [>.............................] - ETA: 0s - loss: 16.0310 - accuracy: 0.4062WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 16.1869 - accuracy: 0.5000 - val_loss: 16.3578 - val_accuracy: 0.3649
Epoch 96/100
 1/20 [>.............................] - ETA: 0s - loss: 16.3578 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 16.5148 - accuracy: 0.5000 - val_loss: 16.6876 - val_accuracy: 0.3649
Epoch 97/100
 1/20 [>.............................] - ETA: 0s - loss: 16.6876 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 16.8489 - accuracy: 0.5000 - val_loss: 17.0268 - val_accuracy: 0.3649
Epoch 98/100
 1/20 [>.............................] - ETA: 0s - loss: 17.0268 - accuracy: 0.5625WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 17.1824 - accuracy: 0.5000 - val_loss: 17.3559 - val_accuracy: 0.3649
Epoch 99/100
 1/20 [>.............................] - ETA: 0s - loss: 17.3559 - accuracy: 0.4688WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 17.5153 - accuracy: 0.5000 - val_loss: 17.6932 - val_accuracy: 0.3649
Epoch 100/100
 1/20 [>.............................] - ETA: 0s - loss: 17.6932 - accuracy: 0.5312WARNING:tensorflow:Early stopping conditioned on metric `categorical_crossentropy` which is not available. Available metrics are: loss,accuracy,val_loss,val_accuracy
20/20 [==============================] - 0s 2ms/step - loss: 17.8582 - accuracy: 0.5000 - val_loss: 18.0397 - val_accuracy: 0.3649

## Save the data

In [38]:
train_X = X_train
train_y = y_train # train_target is now a series objecttrain_df.to_csv('aaw_train_df.csv', index=False)
test_X = X_test
test_y = y_test # validation_target is now a series object


train_X.to_csv('aaw_train_X.csv', index=False)
train_y.to_csv('aaw_train_y.csv', index=False)
test_X.to_csv('aaw_test_X.csv', index=False)
test_y.to_csv('aaw_test_y.csv', index=False)